package database

enum PolicyType {
     NOT_IN_FORCE_TRUE,
     OUTSTANDING_BALANCED_TRUE,
     IN_FORCE_LESS_THAN_A_DAY_TRUE,
     CUSTOMER_BARRED_ACC,
     CUSTOMER_BARRED_UW,
     CUSTOMER_BARRED_UW_VAL,
     RENEWAL_CYCLE_TRUE,
     TSV_POB,
     TIA_RETURNS_FALSE
}